/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'zdm-icons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-angle-left-double-o-thin': '&#xe982;',
		'icon-angle-left-double-o': '&#xe983;',
		'icon-angle-right-double-o-thin': '&#xe984;',
		'icon-angle-right-double-o': '&#xe985;',
		'icon-ashbin-o-thin': '&#xe986;',
		'icon-ashbin-o': '&#xe987;',
		'icon-calendar-o-thin': '&#xe988;',
		'icon-calendar-o': '&#xe989;',
		'icon-change-o-thin': '&#xe98a;',
		'icon-change-o': '&#xe98b;',
		'icon-edit-o-thin': '&#xe98c;',
		'icon-edit-o': '&#xe98d;',
		'icon-question-o-thin': '&#xe98e;',
		'icon-question-o': '&#xe98f;',
		'icon-crown': '&#xe97e;',
		'icon-biaoqing-moon': '&#xe97f;',
		'icon-biaoqing-star': '&#xe980;',
		'icon-biaoqing-sun': '&#xe981;',
		'icon-check-circle': '&#xe97a;',
		'icon-check-o-thin': '&#xe97b;',
		'icon-check-o': '&#xe97c;',
		'icon-exclamation-circle': '&#xe97d;',
		'icon-refresh-circle': '&#xe977;',
		'icon-refresh-o-thin': '&#xe978;',
		'icon-refresh-o': '&#xe979;',
		'icon-buzhi-circle': '&#xe96f;',
		'icon-contents-o-thin': '&#xe970;',
		'icon-contents-o': '&#xe971;',
		'icon-mobile-o': '&#xe972;',
		'icon-rss-circle': '&#xe973;',
		'icon-wechat-circle': '&#xe974;',
		'icon-weibo-circle': '&#xe975;',
		'icon-zhi-circle': '&#xe976;',
		'icon-angle-down-o-thin': '&#xe900;',
		'icon-angle-down-o': '&#xe901;',
		'icon-angle-down': '&#xe902;',
		'icon-angle-left-o-thin': '&#xe903;',
		'icon-angle-left-o': '&#xe904;',
		'icon-angle-left': '&#xe905;',
		'icon-angle-right-o-thin': '&#xe906;',
		'icon-angle-right-o': '&#xe907;',
		'icon-angle-right': '&#xe908;',
		'icon-angle-up-o-thin': '&#xe909;',
		'icon-angle-up-o': '&#xe90a;',
		'icon-angle-up': '&#xe90b;',
		'icon-bag-o-thin': '&#xe90c;',
		'icon-bag-o': '&#xe90d;',
		'icon-basketball-o-thin': '&#xe90e;',
		'icon-basketball-o': '&#xe90f;',
		'icon-bear-o-thin': '&#xe910;',
		'icon-bear-o': '&#xe911;',
		'icon-book-o-thin': '&#xe912;',
		'icon-book-o': '&#xe913;',
		'icon-building-o-thin': '&#xe914;',
		'icon-building-o': '&#xe915;',
		'icon-buoy': '&#xe916;',
		'icon-buzhi-o-thin': '&#xe917;',
		'icon-buzhi-o': '&#xe918;',
		'icon-car-o-thin': '&#xe919;',
		'icon-car-o': '&#xe91a;',
		'icon-category-o-thin': '&#xe91b;',
		'icon-category-o': '&#xe91c;',
		'icon-chicken-o-thin': '&#xe91d;',
		'icon-chicken-o': '&#xe91e;',
		'icon-comment-o-thin': '&#xe91f;',
		'icon-comment-o': '&#xe920;',
		'icon-comment': '&#xe921;',
		'icon-computer-o-thin': '&#xe922;',
		'icon-computer-o': '&#xe923;',
		'icon-credit-card-o-thin': '&#xe924;',
		'icon-credit-card-o': '&#xe925;',
		'icon-decline-o-thin': '&#xe926;',
		'icon-decline-o': '&#xe927;',
		'icon-diamond-o-thin': '&#xe928;',
		'icon-diamond-o': '&#xe929;',
		'icon-douban': '&#xe92a;',
		'icon-drawer': '&#xe92b;',
		'icon-face-o-thin': '&#xe92c;',
		'icon-face-o': '&#xe92d;',
		'icon-face': '&#xe92e;',
		'icon-fire-o-thin': '&#xe92f;',
		'icon-fire-o': '&#xe930;',
		'icon-gift-o-thin': '&#xe931;',
		'icon-gift-o': '&#xe932;',
		'icon-grid-o-thin': '&#xe933;',
		'icon-grid-o': '&#xe934;',
		'icon-info-circle': '&#xe935;',
		'icon-info-mark-o-thin': '&#xe936;',
		'icon-info-mark-o': '&#xe937;',
		'icon-list-o-thin': '&#xe938;',
		'icon-list-o': '&#xe939;',
		'icon-microphone-o-thin': '&#xe93a;',
		'icon-microphone-o': '&#xe93b;',
		'icon-mobile': '&#xe93c;',
		'icon-more': '&#xe93d;',
		'icon-pacifier-o-thin': '&#xe93e;',
		'icon-pacifier-o': '&#xe93f;',
		'icon-pennant-o-thin': '&#xe940;',
		'icon-pennant-o': '&#xe941;',
		'icon-plus-circle': '&#xe942;',
		'icon-plus-o-thin': '&#xe943;',
		'icon-plus-o': '&#xe944;',
		'icon-price-tag-o-thin': '&#xe945;',
		'icon-price-tag-o': '&#xe946;',
		'icon-printer-o-thin': '&#xe947;',
		'icon-printer-o': '&#xe948;',
		'icon-qq': '&#xe949;',
		'icon-qzone': '&#xe94a;',
		'icon-robot': '&#xe94b;',
		'icon-rss': '&#xe94c;',
		'icon-search-o-thin': '&#xe94d;',
		'icon-search-o': '&#xe94e;',
		'icon-service': '&#xe94f;',
		'icon-shampoo-o-thin': '&#xe950;',
		'icon-shampoo-o': '&#xe951;',
		'icon-share-o-thin': '&#xe952;',
		'icon-share-o': '&#xe953;',
		'icon-shoes-o-thin': '&#xe954;',
		'icon-shoes-o': '&#xe955;',
		'icon-shop-o-thin': '&#xe956;',
		'icon-shop-o': '&#xe957;',
		'icon-sofa-o-thin': '&#xe958;',
		'icon-sofa-o': '&#xe959;',
		'icon-star-o-thin': '&#xe95a;',
		'icon-star-o': '&#xe95b;',
		'icon-star': '&#xe95c;',
		'icon-suitcase-o-thin': '&#xe95d;',
		'icon-suitcase-o': '&#xe95e;',
		'icon-thumb-up-o-thin': '&#xe95f;',
		'icon-thumb-up-o': '&#xe960;',
		'icon-thumb-up': '&#xe961;',
		'icon-times-circle': '&#xe962;',
		'icon-times-o-thin': '&#xe963;',
		'icon-times-o': '&#xe964;',
		'icon-toilet-paper-o-thin': '&#xe965;',
		'icon-toilet-paper-o': '&#xe966;',
		'icon-topic-o-thin': '&#xe967;',
		'icon-topic-o': '&#xe968;',
		'icon-washer-o-thin': '&#xe969;',
		'icon-washer-o': '&#xe96a;',
		'icon-wechat': '&#xe96b;',
		'icon-weibo': '&#xe96c;',
		'icon-zhi-o-thin': '&#xe96d;',
		'icon-zhi-o': '&#xe96e;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
